language: node_js
notifications:
  email: true
node_js: 16.15.0
cache:
  directories:
    - "node_modules"
before_install:
  - npm install
jobs:
  include:
    - stage: test
      script:
        - npm run test
        - CI=false npm run build
