export const SET_SIMILAR_MOVIES_LIST_SUCCESS = 'SET_SIMILAR_MOVIES_LIST_SUCCESS';
export const SET_SIMILAR_MOVIES_LIST_FAIL = 'SET_SIMILAR_MOVIES_LIST_FAIL';

export const SET_SELECTED_MOVIE_INFO_SUCCESS = "SET_SELECTED_MOVIE_INFO_SUCCESS"
export const SET_SELECTED_MOVIE_INFO_FAIL = "SET_SELECTED_MOVIE_INFO_FAIL"

export const SET_SELECTED_MOVIE_CAST_SUCCESS = "SET_SELECTED_MOVIE_CAST_SUCCESS"
export const SET_DIRECTOR_SUCCESS = "SET_DIRECTOR_SUCCESS"
export const SET_MOVIE_CREDITS_FAIL = "SET_MOVIE_CREDITS_FAIL"