export const SET_GENRE_MAP_SUCCESS = 'SET_GENRE_MAP_SUCCESS';
export const SET_GENRE_MAP_FAIL = 'SET_GENRE_MAP_FAIL';

export const SET_FEATURED_LIST_SUCCESS = 'SET_FEATURED_LIST_SUCCESS';
export const SET_FEATURED_LIST_FAIL = 'SET_FEATURED_LIST_FAIL';

export const SET_SHOWN_LIST_SUCCESS = 'SET_SHOWN_LIST_SUCCESS';
export const SET_TOTAL_PAGES_SUCCESS = 'SET_TOTAL_PAGES_SUCCESS';
export const SET_TOTAL_RESULTS_SUCCESS = 'SET_TOTAL_RESULTS_SUCCESS';
export const SEARCH_FILMS_FAIL = 'SEARCH_FILMS_FAIL';

export const SEARCH_ISEMPTY = 'SEARCH_ISEMPTY';

export const SORTBY_RATING = 'SORTBY_RATING';

export const SET_SEARCH_VAL = 'SET_SEARCH_VAL';

export const SET_RESULT_PAGE = 'SET_RESULT_PAGE';